### ISSUE TITLE
(post comments) Intoduction to Cobol to Hive Serde blogs

### ISSUE THREAD

**Issue by rbheemana** [rbheemana/Cobol-to-Hive#1]

**Comment by rbheemana** [comment]
Testing

**Comment by manichinnari555** [comment]
Hello rbheemana,

I was following this blog since a while and wanted to try in our system, however  i have just noticed that there is no JAR file available in the target folder, may I know where can i find and how I can try it?

**Comment by manichinnari555** [comment]
Hi, 

However I got some jar file in your activity folder, I have tried adding the jar and create the table, I am getting the following error....

Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. Cannot validate serde: org.savy3.hadoop.hive.serde2.cobol.CobolSerde
hive>

**Comment by manichinnari555** [comment]
hive> CREATE TABLE Cobol2Hive
    > ROW FORMAT SERDE 'org.savy3.hadoop.hive.serde2.cobol.CobolSerde'
    > LOCATION '/tmp/testdata/input_file.txt'
    > TBLPROPERTIES ('cobol.layout'='01 WS-VAR. 05 WS-NAME PIC X(12). 05 WS-MARKS-LENGTH PIC 9(2). 05 WS-marks OCCURS 0 to 6 TIMES DEPENDING ON WS-MARKS-LENGTH. 10 WS-MARK PIC 999. 05 WS-NICKNAME PIC X(6)');
FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. Cannot validate serde: org.savy3.hadoop.hive.serde2.cobol.CobolSerde

**Comment by rbheemana** [comment]
@manichinnari555: I recommend creating your own jar file from the code I provided. However for a quick test i have added jar file in location https://github.com/rbheemana/Cobol-to-Hive/tree/gh-pages/target

Serde expects the input file to be in binary format, could you please check file '/tmp/testdata/input_file.txt' is in binary format. 

File needs to be in raw binary format. The example I provided in blog is for understand, actual binary files will be unreadable by human eye.
Jar works for any cobol layout.
To test u need to actually get the file from mainframe using the method I specified in blog. Just Creating a text file won't work as mainframe files are in EBCIDIC format not ASCII format.

It should something look like below:
ADD JAR CobolSerde.jar
CREATE EXTERNAL TABLE default.mani
ROW FORMAT SERDE 'com.savy3.hadoop.hive.serde2.cobol.CobolSerDe'
STROED AS INPUTFORMAT 'org.apache.hadoop.mapred.FixedLengthInputFormat'
OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.IgnoreKeyTextOutputFormat'
LOCATION '/user/manichinnari/bin_file.txt'
TBLPROPERTIES ('cobol.layout.url'='/user/manichinnari/copybooks/CKNNEWTN.txt','fb.length'='450')

**Comment by manichinnari555** [comment]
Thanks for the note.

Yes, we want to test with the sample data and the jar before we start customizing it.

Yes, it is binary data, however while creating the table, i am getting the following error. Do you have any idea about this error and how to fix it.

FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. Cannot validate serde: org.savy3.hadoop.hive.serde2.cobol.CobolSerde

**Comment by rbheemana** [comment]
I will look into error, could you please send the sample file you are using.

Sent from Outlook on iOS




On Wed, Apr 13, 2016 at 10:42 AM -0700, "manichinnari555" <notifications@github.com> wrote:












Thanks for the note.



Yes, we want to test with the sample data and the jar before we start customizing it.



Yes, it is binary data, however while creating the table, i am getting the following error. Do you have any idea about this error and how to fix it.



FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. Cannot validate serde: org.savy3.hadoop.hive.serde2.cobol.CobolSerde

**Comment by manichinnari555** [comment]
For now I am using the same file that you have provided in you blog. I want to see if i could use the file to create the table.

I think your jar works only the file layout that you have provided in your blog? is my understanding is correct?

**Comment by rbheemana** [comment]
No file needs to be in raw binary format. The example I provided in blog is for understand, actual binary files will be unreadable by human eye.
Jar works for any cobol layout.
To test u need to actually get the file from mainframe using the method I specified in blog. Just Creating a text file won't work as mainframe files are in EBCIDIC format not ASCII format.

Sent from Outlook on iOS




On Wed, Apr 13, 2016 at 10:56 AM -0700, "manichinnari555" <notifications@github.com> wrote:












For now I am using the same file that you have provided in you blog. I want to see if i could use the file to create the table.



I think your jar works only the file layout that you have provided in your blog? is my understanding is correct?

**Comment by manichinnari555** [comment]
Hello,

Got it, here is the binary file and the copybook layout that i am working with. Please let me if you need any more info.
[bin_file.txt](https://github.com/rbheemana/Cobol-to-Hive/files/217744/bin_file.txt)
[CKNNEWTN.txt](https://github.com/rbheemana/Cobol-to-Hive/files/217745/CKNNEWTN.txt)

**Comment by manichinnari555** [comment]
Hello,

I have shared my file and copybook did you got a chance to look into that?

**Comment by rbheemana** [comment]
Did you add jar to hive before you exceuted the create table?

**Comment by manichinnari555** [comment]
Yes, I did added.

Add jar and the jar. Also copied to hive lib folder.

**Comment by rbheemana** [comment]
I see things some things in query that needs to be fixed.

1. serde starts with com not org
2. Need to specify input format and output format
3. try placing the copybook in hdfs path since it is big and use cobol.layout.url
4. specify the fixed length property (if it is fixed length file)

It should something look like below: 
ADD JAR CobolSerde.jar
CREATE EXTERNAL TABLE default.mani
ROW FORMAT SERDE 'com.savy3.hadoop.hive.serde2.cobol.CobolSerde'
INPUTFORMAT 'org.apache.hadoop.mapred.FixedLengthInputFormat'
OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.IgnoreKeyTextOutputFormat'
LOCATION '/user/manichinnari/bin_file.txt'
TBLPROPERTIES ('cobol.layout.url'='/user/manichinnari/copybooks/CKNNEWTN.txt','fb.length'='450');

**Comment by manichinnari555** [comment]
Hello, 
Thanks for in detailed steps, I have tried these, however still facing same issue. Please let me know if we can take this offline and work on this.

**Comment by rbheemana** [comment]
Please connect me :ram.manohar2708@gmail.com

**Comment by rbheemana** [comment]
@manichinnari555: I cleaned up your comments as the issue is resolved by using  below link http://www.cloudera.com/documentation/enterprise/latest/topics/sg_sentry_service_config.html?scroll=concept_mvn_kvs_lr#concept_mvn_kvs_lr

**Comment by manichinnari555** [comment]
Hello Ram,

Thanks, but I would like to let you know that, I am downloaded new SANBOX and executed previous steps that you have shared and it worked, but I am still not sure why I am getting the PIC clause issue, I am using the same copybook that I have share with you. If you have any information, please let me know, i will keep working on that. thanks.

Regards,

**Comment by manichinnari555** [comment]
Hello Ram,

Things are much better now and lot of things are working, but "could you please add support of COMP and COMP4 variables"?

## 

Regards,

**Comment by manichinnari555** [comment]
Hello Ram,

As discussed please find the attached copybook and the sample file.

Regards

**Comment by manichinnari555** [comment]
Hello Ram,

Please find the updated COBOL

 layout with all the fields init.

Regards,

**Comment by manichinnari555** [comment]
Hello Ram,

Please find the describe output.
[session.zip](https://github.com/rbheemana/Cobol-to-Hive/files/245770/session.zip)

**Comment by manichinnari555** [comment]
[bin_file_1.txt](https://github.com/rbheemana/Cobol-to-Hive/files/245993/bin_file_1.txt)

**Comment by manichinnari555** [comment]
Hello Ram,

Many Thanks for looking into the issue and everything seems working on. Really appreciated your help.

Regards,
Venkat

**Comment by manichinnari555** [comment]
Hello Ram,

I have create the table1 using the cobol serde and table 2 with the same ddl but the storage format is different(parquet), later while trying to insert the data into table2 using the fololwing statement, I am getting the below error. Could you please have a look and guide me? 

Is there any error in the SerDe?

Statement:
----------------
insert overwrite  table table2 PARTITION(dt='2016.06.13') select * from table1;

Error:
--------

Caused by: org.apache.hadoop.hive.ql.metadata.HiveException: Hive Runtime Error while processing row {"c5qtsys_detail_clnt_no":"2430","c5qtsys_detail_acct_no":"4510109900005012   ","c5qtsys_detail_log_date":20160406,"c5qtsys_detail_auth_log_time":151837,"c5qtsys_detail_maint_date":20151020,"c5qtsys_detail_maint_time":131009,"c5qtsys_detail_operator_id":"BLANMA","c5qtsys_detail_prev_frd_flag":"N","c5qtsys_detail_curr_frd_flag":"N","c5qtsys_detail_trans_amt":"+0000003.61","c5qtsys_detail_message_type":100,"c5qtsys_detail_reference_no":"    ","c5qtsys_detail_trans_date":2015289,"c5qtsys_detail_trans_id":"305289672360311 ","c5qtsys_detail_trans_apvl_cd":"010837","c5qtsys_detail_merchant_class":"8661","filler":"                                      "}
        at org.apache.hadoop.hive.ql.exec.MapOperator.process(MapOperator.java:545)
        at org.apache.hadoop.hive.ql.exec.tez.MapRecordSource.processRow(MapRecordSource.java:83)
        ... 17 more
Caused by: java.lang.ClassCastException: org.apache.hadoop.io.Text cannot be cast to org.apache.hadoop.hive.serde2.io.ParquetHiveRecord
        at org.apache.hadoop.hive.ql.io.parquet.write.ParquetRecordWriterWrapper.write(ParquetRecordWriterWrapper.java:124)
        at org.apache.hadoop.hive.ql.exec.FileSinkOperator.process(FileSinkOperator.java:753)
        at org.apache.hadoop.hive.ql.exec.Operator.forward(Operator.java:838)
        at org.apache.hadoop.hive.ql.exec.SelectOperator.process(SelectOperator.java:88)
        at org.apache.hadoop.hive.ql.exec.Operator.forward(Operator.java:838)
        at org.apache.hadoop.hive.ql.exec.TableScanOperator.process(TableScanOperator.java:97)
        at org.apache.hadoop.hive.ql.exec.MapOperator$MapOpCtx.forward(MapOperator.java:164)
        at org.apache.hadoop.hive.ql.exec.MapOperator.process(MapOperator.java:535)

**Comment by rajatm91** [comment]
Hi Ram , 

I was trying to upload fixedformat cobol file into the hive table using the serde. But i got following error while query on the table. 

 select \* from Cobol2Hive;
OK
Failed with exception java.io.IOException:java.io.IOException: Partial record(length = 62) found at the end of split.

Could you please help me with this.

Ascii File

Rajat       75SUNNY
Abhinandan  10B
Arpit       44JAIN

Ebcdic File
Ã<81><91><81>Â£@@@@@@@Ã·ÃµÃ¢Ã¤ÃÃÃ¨@%Ã<82><88><89><95><81><95><84><81><95>@@Ã±Ã°Ã@@@@@%Ã<99><97><89>Â£@@@@@@@Ã´Ã´ÃÃÃÃ@@

CobolCopybook

01 WS-VAR.
   05 WS-NAME PIC X(12).
   05 WS-EMPLOYEE-ID PIC 9(2).
   05 WS-NICKNAME PIC X(6)

**Comment by rbheemana** [comment]
@rajatm91 First check the input file size. As it is a FB file, size of the binary file on hadoop should be multiple of 20 (based on copybook supplied). If it is not then the ftpied file is corrupted. Please try re-downloading.

**Comment by randomusernamer** [comment]
Hello @rbheemana !

I really like your project, It looks very useful and I was thinking on use it but I have 2 doubts:
- Is it possible to use the program to transform a EBCDIC file into a ASCII file in HDFS (instead of just read it as ASCII).
- Is it possible to convert an ASCII file/table into an EBCDIC file/table?

Thank you very much in advance,
Best regards

**Comment by rbheemana** [comment]
I do not understand your questions completely, I believe you misunderstood the concept. But file in hdfs will be in EBCIDIC binary format. ASCII conversion happens only when we retrieve a column.

Thanks,
Ram

**Comment by randomusernamer** [comment]
Hi @rbheemana,

I understand the concept of the project. Indeed, I've used the program already to read a EBCDIC file via Hive.

My question is, given that the hardest part is solved (read an EBCDIC file and transform the information to ASCII using Hive), it is possible to use the class to write a file instead to show the information via Hive, Have you done something like this?

And the second question, right now the project reads an EBCDIC file and shows you a Hive table in ASCII format, Would it be possible to do the reverse process? i.e Would it be possible to read a Hive table to write an EBCDIC file in HDFS using this class?

Thank you for your time,
Best regards

**Comment by rbheemana** [comment]
Please see my response inline with your mail

Thanks,
Ram

**Comment by randomusernamer** [comment]
Hi @rbheemana,

I was using the way you proposed, I was just asking If you have implemented the conversion to file to avoid read and interpret the copy again to create the table.

The interest of the ASCII to EBCDIC conversion is to replace some process of mainframe saving MIPS using the Hadoop cluster and then return the file to Host. We know many ways to convert ASCII to EBCDIC (in Host or zLinux) but we were looking for a solution that works for Hadoop to run the process in parallel.

Thanks,
Best regards

**Comment by randomusernamer** [comment]
When I tried the solution you propose It throws an error:

Error: java.io.IOException: java.io.IOException: java.lang.NegativeArraySizeException
        at org.apache.hadoop.hive.io.HiveIOExceptionHandlerChain.handleRecordReaderNextException(HiveIOExceptionHandlerChain.java:121)
        at org.apache.hadoop.hive.io.HiveIOExceptionHandlerUtil.handleRecordReaderNextException(HiveIOExceptionHandlerUtil.java:77)
        at org.apache.hadoop.hive.shims.HadoopShimsSecure$CombineFileRecordReader.doNextWithExceptionHandler(HadoopShimsSecure.java:226)
        at org.apache.hadoop.hive.shims.HadoopShimsSecure$CombineFileRecordReader.next(HadoopShimsSecure.java:136)
        at org.apache.hadoop.mapred.MapTask$TrackedRecordReader.moveToNext(MapTask.java:199)
        at org.apache.hadoop.mapred.MapTask$TrackedRecordReader.next(MapTask.java:185)
        at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:52)
        at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:453)
        at org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)
        at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:163)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1671)
        at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)
Caused by: java.io.IOException: java.lang.NegativeArraySizeException
        at org.apache.hadoop.hive.io.HiveIOExceptionHandlerChain.handleRecordReaderNextException(HiveIOExceptionHandlerChain.java:121)
        at org.apache.hadoop.hive.io.HiveIOExceptionHandlerUtil.handleRecordReaderNextException(HiveIOExceptionHandlerUtil.java:77)
        at org.apache.hadoop.hive.ql.io.HiveContextAwareRecordReader.doNext(HiveContextAwareRecordReader.java:355)
        at org.apache.hadoop.hive.ql.io.CombineHiveRecordReader.doNext(CombineHiveRecordReader.java:105)
        at org.apache.hadoop.hive.ql.io.CombineHiveRecordReader.doNext(CombineHiveRecordReader.java:41)
        at org.apache.hadoop.hive.ql.io.HiveContextAwareRecordReader.next(HiveContextAwareRecordReader.java:116)
        at org.apache.hadoop.hive.shims.HadoopShimsSecure$CombineFileRecordReader.doNextWithExceptionHandler(HadoopShimsSecure.java:224)
        ... 11 more
Caused by: java.lang.NegativeArraySizeException
        at com.savy3.mapreduce.MainframeVBRecordReader.nextKeyValue(MainframeVBRecordReader.java:175)
        at com.savy3.mapred.MainframeVBRecordReader.next(MainframeVBRecordReader.java:63)
        at com.savy3.mapred.MainframeVBRecordReader.next(MainframeVBRecordReader.java:1)
        at org.apache.hadoop.hive.ql.io.HiveContextAwareRecordReader.doNext(HiveContextAwareRecordReader.java:350)
        ... 15 more

Do you have any idea what could it be happening?

Indeed, a "SELECT \* FROM TABLE LIMIT 100" over the EBCDIC to ASCII table is working fine, but "SELECT \* FROM TABLE" (without LIMIT) is returning same error as before: NegativeArraySizeException.

Thank you very much,
Best regards

**Comment by rbheemana** [comment]
None so far.

**Comment by rbheemana** [comment]
Looks like VB record reader has a bug. Please add a defect and provide me examples, will take a look when I get time.

**Comment by datawarlock** [comment]
How did you get the file into Hadoop?  I have found with the VB files you need to make sure that you transfer the files with the following settings:
binary
quote site RDW
quote site blksize=<your blocksize>

If you do not do this, what happens is the limit is looking at the first split of the file and there is no issue.  The full query will return data across splits and without the block size it will not do the split correctly.  Normally when doing RDW the BDW (block delimiter) will come but when going from MF to Linux/windows the FTP process strips the BDW meaning it won't know when the block ends and the new one begins.
Remember that VB is varying character length but it is blocked so the blocks should be consistent.

Try that and if it does not work then there might be a bug.

**Comment by randomusernamer** [comment]
You guys are just great!!

It was a problem with the FTP, as you said the file was corrupt; after doing the FTP properly, I can see the data and materialize it in a file perfectly. All the selects works as expected. Thank you very much!!!
Best regards,
And again, thanks for your time

**Comment by tejasbharambe** [comment]
We have one ebcdic sample file. 
It is stored in /user/hive/warehouse/ebcdic_test_file.txt


Cobol layout of the file is stored in /user/hive/Warehouse/CobolSerde.cob


We are running on Hue browser query editor. 
We also tried in CLI. 
But the same error is coming 


We have added CobolSerde.jar. 
Via 
Add jar /home/cloudera/Desktop/CobolSerde.jar 

It has been added successfully. Proof via LIST JARS. 



Query 
-----------
CREATE EXTERNAL TABLE cobol2Hve 
ROW FORMAT SERDE 'com.savy3.hadoop.hive.serde2.cobol.CobolSerDe' 
STORED AS INPUTFORMAT 'org.apache.hadoop.mapred.FixedLengthInputFormat' 
OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.IgnoreKeyTextOutputFormat' 
LOCATION '/user/hive/warehouse/ebcdic_test_file.txt' 
TBLPROPERTIES ('cobol.layout.url'='/user/hive/warehouse/CobolSerDe.cob','fb.length'='159');



Error while processing statement: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. Cannot validate serde: com.savy3.hadoop.hive.serde2.cobol.CobolSerDe


1. Why is the error coming? 
2. What is fb.length?

**Comment by jkckiran** [comment]
Hi Bheemana, This is a very good tool for many of us. You guys are great.

I just have few questions in using this tool. 
- Both the input file and its corresponding layout / copybook file should be in EBCDIC format or only the input file should be in EBCDIC and the layout can be in .txt format ?
- And the input file along with its layout file should be available in HDFS or the CobolSerde can fetch them from Unix file system as well. I assume both should be in HDFS. 

Please confirm

**Comment by rbheemana** [comment]
Input file should be in EBCDIC format, copy book in text file. Both files needs to be hdfs.    
 
Thanks,
Ram

**Comment by johnplt** [comment]
I have this error when i try to execute this : "Unsupported major.minor version 52.0"

Any help ?

John

**Comment by manichinnari555** [comment]
Hello,

Please find the inline comments.

Sent from my iPhone

> On Apr 13, 2017, at 3:00 AM, jkckiran <notifications@github.com> wrote:
> 
> Hi Bheemana, This is a very good tool for many of us. You guys are great.
> 
> I just have few questions in using this tool.
> 
> Both the input file and its corresponding layout / copybook file should be in EBCDIC format or only the input file should be in EBCDIC and the layout can be in .txt format ?
Ven: only input file should be EBCDIC and the layout in txt.
> And the input file along with its layout file should be available in HDFS or the CobolSerde can fetch them from Unix file system as well. I assume both should be in HDFS.
Yes, both should be in hdfs.

**Comment by johnplt** [comment]
Hi @rbheema,

Thank you for reply but I don’t think these comments answer to my issue.
My all files are stored on HDFS. The error seems to have link to a version issue but I don’t know which version.

May be java version between jar and server ?

John

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : manichinnari555<mailto:notifications@github.com>
Envoyé le :mercredi 31 mai 2017 14:53
À : rbheemana/Cobol-to-Hive<mailto:Cobol-to-Hive@noreply.github.com>
Cc : johnplt<mailto:johnplt@live.com>; Comment<mailto:comment@noreply.github.com>
Objet :Re: [rbheemana/Cobol-to-Hive] (post comments) Intoduction to Cobol to Hive Serde blogs (#1)

Hello,

Please find the inline comments.

Sent from my iPhone

> On Apr 13, 2017, at 3:00 AM, jkckiran <notifications@github.com> wrote:
>
> Hi Bheemana, This is a very good tool for many of us. You guys are great.
>
> I just have few questions in using this tool.
>
> Both the input file and its corresponding layout / copybook file should be in EBCDIC format or only the input file should be in EBCDIC and the layout can be in .txt format ?
Ven: only input file should be EBCDIC and the layout in txt.
> And the input file along with its layout file should be available in HDFS or the CobolSerde can fetch them from Unix file system as well. I assume both should be in HDFS.
Yes, both should be in hdfs.

**Comment by johnplt** [comment]
I finally succesed yesterday to create my table with cobol serde by execute it in the hive shell instead of HUE.

But when I do a "select" on my created table, all values are null 

NULL    NULL    NULL    ????????????&????????   NULL    ??????? ????????????    ?????????       NULL    NULL    NULL    NULL    NULL    NULL    NULL    ?       ?      ??       ??      ???     NULL    NULL    ?       NULL    NULL    ??      ???     ?       NULL    NULL    ??????????      ?       ??      NULL    NULL    NULL    NULL   NULL     ?       ??????????      NULL    ?       NULL    NULL    ??????????????????????  NULL    NULL    ??
NULL    NULL    NULL    ????????????&???????    NULL    ??????? ????????????    ?????????       NULL    NULL    NULL    NULL    NULL    NULL    NULL    ?       ?      ??       ??      ???     NULL    NULL    ?       NULL    NULL    ??      ???     ?       NULL    NULL    ??????????      ?       ??      NULL    NULL    NULL    NULL   NULL     ?       ??????????      NULL    ?       NULL    NULL    ??????????????????????  NULL    NULL    ??

Anyone get this happenned ?

John

**Comment by sanch002** [comment]
Hi Ram 
i have the jar in my lib folder and ran the following command from the lib path with the actual values  but i am getting the following error and not sure why .By the way this is for a VSAM file. Can you please let me know if you know what the reason might be ? I would really appreciate it. Thanks!

hadoop jar CobolSerde.jar com/savy3/util/FTPtoHDFS mainframe:port username password mainframeinputfilename hadooppathforoutput 


Connected to mainframe on 21 
reply for LITERAL200 SITE command was accepted 

FTP Start Time : 2017-06-01 17:30:39.124 
Exception in thread "main" java.lang.NullPointerException 
        at org.apache.hadoop.io.IOUtils.copyBytes(IOUtils.java:85) 
        at org.apache.hadoop.io.IOUtils.copyBytes(IOUtils.java:59) 
        at org.apache.hadoop.io.IOUtils.copyBytes(IOUtils.java:119) 
        at com.savy3.util.FTPtoHDFS.main(FTPtoHDFS.java:50) 
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) 
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
        at java.lang.reflect.Method.invoke(Method.java:606) 
        at org.apache.hadoop.util.RunJar.run(RunJar.java:221) 
        at org.apache.hadoop.util.RunJar.main(RunJar.java:136)

**Comment by rbheemana** [comment]
@johnplt Please follow the instructions in this link to compile the code corectly https://github.com/rbheemana/Cobol-to-Hive/issues/20

The issue you mentioned arises when the Java version on which you compiled is different from Java version on which you executed.

Please try compiling again and check if the NULL issue still persists.

**Comment by rbheemana** [comment]
@sanch002 could you run manual FTP commands from the edge node, to verify you can establish FTP connection to FTP server. I believe Firewall port are not open to make an FTP connection from your cluster to FTP server.

**Comment by johnplt** [comment]
Thanks for the reply @rbheemana. I failed to create the jar file. It seems that it does not success to find some packages, Example : package org.apache.hadoop.hive.serde2.objectinspector does not exist.

May be it's the definition of the hadoop home and hive home (set %classpath%=%HADOOP_HOME%*;%HIVE_HOME%\lib*;)

I am on Unix and I define the classpath like that : classpath=/usr/bin/hadoop:/usr/bin/hive

That seems to be wrong. Anyone nows how to retrieve the hadoop and hive home ?

**Comment by rbheemana** [comment]
@johnplt Please check with your hadoop adminstrator, different distributions have different locations. Also it can be custom defined. So there is no single answer for it. Best bet is to check with person who installed your cluster.

**Comment by shankardh** [comment]
Hi Ram,
What special care need to be taken to load variable length file?
have created sample file given in problem description and  FTP'ed using option 6 in mainframe in binary format. created cobol copybook is also as given. But, still getting Partial record (length = ***) found at the end of split error.
ADD JAR /CobolSerde.jar;
CREATE EXTERNAL TABLE test
ROW FORMAT SERDE 'com.savy3.hadoop.hive.serde3.cobol.CobolSerDe' 
STORED AS
INPUTFORMAT 'com.savy3.mapred.MainframeVBInputFormat'
OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.IgnoreKeyTextOutputFormat'
LOCATION '/user/test'
TBLPROPERTIES ('cobol.layout.url'='/user/copybook/cobol.cp')

copybook is -- 
01 WS-VAR.
  05 WS-NAME PIC X(12).
  05 WS-MARKS-LENGTH PIC 9(2).
  05 WS-marks OCCURS 0 to 25 TIMES DEPENDING ON WS-MARKS-LENGTH.
    10 WS-MARK PIC 999.
  05 WS-NICKNAME PIC X(6).

**Comment by rbheemana** [comment]
Please download with RDW byte to determine length of each record
  

  
  

  
  
>

**Comment by any2xml** [comment]
Hi Bheemana
Thank you for creating a very useful SERDE. I have variable blocked file of large size and tons of columns. Just imported the project and performed mvn install to obtain the jar. Before proceeding I have these questions:

1. The built jar is named Cobol-to-Hive-1.1.0.jar but your instruction says CobolSerde.jar. Did I miss something? But I see all the required classes in Cobol-to-Hive-1.1.0.jar.
2. Should I transfer the VB file "as is" to HDFS or have it unblocked? You mentioned RDW but the file contains a BDW at the beginning of each block with multiple RDW. Is there any pre-processing required?
3. COBOL can throw a lot of curve balls like RENAMES, CONDITION-NAMEs, PIC with SIGN, zoned decimal, packed decimal with sign etc.It would be good to know any  limitations in features and size. Are there any I need to be aware of?

4. Does it handle multipe ODO (Occurs Depending Upon)  in each record?
5. Is there a file size / max column limitations? I am working on files that are 30GB and more. Some of them have 4K columns.

I would appreciate a response at your earliest. Thanks

**Comment by rajeshmese** [comment]
Error: Error while compiling statement: FAILED: SemanticException 1:14 Input format must implement InputFormat.  How to resolve this issue. HDP 3 environment.

**Comment by rbheemana** [comment]
@any2xml 
1. The built jar is named Cobol-to-Hive-1.1.0.jar but your instruction says CobolSerde.jar. Did I miss something? But I see all the required classes in Cobol-to-Hive-1.1.0.jar. 
1.1.0 is the updated version

2. Should I transfer the VB file "as is" to HDFS or have it unblocked? You mentioned RDW but the file contains a BDW at the beginning of each block with multiple RDW. Is there any pre-processing required? 
I believe BDW should also work, I have not tried. Let me know if you face any issues.
 
3. COBOL can throw a lot of curve balls like RENAMES, CONDITION-NAMEs, PIC with SIGN, zoned decimal, packed decimal with sign etc.It would be good to know any  limitations in features and size. Are there any I need to be aware of?
It solves most of them, but I haven't handled for RENAMES and CONDITION-NAMEs. Create an issue for desired functionality, i will try to code in my free time.


4. Does it handle multipe ODO (Occurs Depending Upon)  in each record?
Yes it does.

5. Is there a file size / max column limitations? I am working on files that are 30GB and more. Some of them have 4K columns.
No limitations.

**Comment by rbheemana** [comment]
@rajeshmese Please let me know the steps how you tried to compile

**Comment by thenervousgeek** [comment]
Hi I tried to create a table as below, but I get an error , can anyone please help.

Some notices:

Jar file (CobolSerde.jar) is in hdfs
datafile.txt is a text file which is in hdfs aswell
COPYBOOK.TXT is the copybook which is a text file residing in hdfs as well.

ADD JAR /user/cloudera/copybooks/CobolSerde.jar;
CREATE EXTERNAL TABLE cobol2hive
ROW FORMAT SERDE 'com.savy3.cobolserde.CobolSerde'
STORED AS INPUTFORMAT 'org.apache.hadoop.mapred.FixedLenghtInputFormat'
OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.IgnoreKeyTextOutputFormat'
LOCATION '/user/hive/warehouse/datafile.txt'
TBLPROPERTIES ('cobol.layout.url'='/user/cloudera/copybooks/COPYBOOK.TXT','fb.length'='130');

--Running this command:
ADD JAR /user/cloudera/copybooks/CobolSerde.jar;

delivers the following error:

AnalysisException: Syntax error in line 1:undefined: ADD JAR /user/cloudera/copybooks/CobolSerde.jar ^ Encountered: ADD Expected: ALTER, COMPUTE, CREATE, DELETE, DESCRIBE, DROP, EXPLAIN, GRANT, INSERT, INVALIDATE, LOAD, REFRESH, REVOKE, SELECT, SET, SHOW, TRUNCATE, UPDATE, UPSERT, USE, VALUES, WITH CAUSED BY: Exception: Syntax error

--Running the whole code altogether returns this Error:

AnalysisException: Syntax error in line 3:undefined: ROW FORMAT SERDE 'com.savy3.cobolserde.CobolSerde' ^ Encountered: IDENTIFIER Expected: DELIMITED CAUSED BY: Exception: Syntax error

**Comment by manichinnari555** [comment]
Hello All,

I need a favour. I am not able to recreate the jar.

Can someone please share jar or the location with me ASAP, really appreciated your help with this. 

Regards,
Venkat

**Comment by rbheemana** [comment]
From below error, looks like you do not have ADD permissions.

**Comment by manichinnari555** [comment]
Hello Ram,

Can you please help with the jar?

Also, I see in the git some part of the code is commented out. Can you please help me? 

Regards,
Venkat
